### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_training'

### ISSUE THREAD

**Issue by jiamingzhang94** [LiYingwei/Regional-Homogeneity#1]
In > region_norm_ops.py,
line 55
`    # 3. normalization
    bn_output = BatchNorm('bn', feed2bn, axis=3, gamma_initializer=gamma_initializer,
                          internal_update=True)`

It seems that calling `BatchNorm` in tensorpack will cause this error. I've tried several versions of tensorpack without solving this bug

**Comment by LiYingwei** [comment]
You can see [this link](https://github.com/tensorpack/tensorpack/issues/201) to have a better understanding of this issue.

If you cannot address this issue by the above link, I am willing to learn more details so that I can reproduce this error.

**Comment by LiYingwei** [comment]
Feel free to reopen this.
